name: Build SingBox Configs

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build configs
        run: |

          SUB=$(curl -s "https://raw.githack.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Mobile.txt" | tr -d '\r')

          ALL=$(echo "$SUB" | grep -E '^(vless|vmess|trojan)://')

          RUSSIA=$(echo "$ALL" | grep -Ei 'russia' || true)

          NON_RUSSIA=$(echo "$ALL" | grep -Evi 'russia' || true)

          make_config () {
            SIZE=$1
            RU_PREF=$2
            OUT=$3

            RU=$(echo "$RUSSIA" | head -n "$RU_PREF")
            RU_COUNT=$(echo "$RU" | grep -c . || true)

            NEED=$((SIZE - RU_COUNT))

            NONRU=$(echo "$NON_RUSSIA" | shuf | head -n "$NEED")

            FINAL=$(printf "%s\n%s\n" "$RU" "$NONRU" | grep .)

            echo "Building $OUT with $(echo "$FINAL" | grep -c .) nodes..."

            jq -n --arg input "$FINAL" '{
              core: "singbox",
              input: $input,
              options: {
                addTun: true,
                addSocks: true,
                genClashSecret: false,
                useExtended: false
              }
            }' \
            | curl -sS -X POST "https://api.web2core.workers.dev/" \
                -H "Content-Type: application/json" \
                --data-binary @- \
            > "$OUT"
          }

          make_config 5 3 config5.json
          make_config 7 5 config7.json
          make_config 10 8 config10.json

          # PURE FOREIGN
          make_foreign () {
            SIZE=$1
            OUT=$2

            FOREIGN=$(echo "$NON_RUSSIA" | shuf | head -n "$SIZE")

            jq -n --arg input "$FOREIGN" '{
              core: "singbox",
              input: $input,
              options: {
                addTun: true,
                addSocks: true,
                genClashSecret: false,
                useExtended: false
              }
            }' \
            | curl -sS -X POST "https://api.web2core.workers.dev/" \
                -H "Content-Type: application/json" \
                --data-binary @- \
            > "$OUT"
          }

          make_foreign 5 config5_foreign.json
          make_foreign 10 config10_foreign.json

          # shuffled duplicates (RU configs)
          make_config 5 3 config5_b.json
          make_config 7 5 config7_b.json
          make_config 10 8 config10_b.json


      - name: Commit configs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add config*.json

          git commit -m "extended multi-config system" || exit 0

          git push
